name: CI
on: 
  pull_request:
    branches: ["develop"]
jobs:
  build-and-run:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
    
      - name: Build project
        run: mvn clean install -DskipTests
        
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Run project
        run: mvn -pl jhotdraw-samples/jhotdraw-samples-misc exec:java -Dexec.mainClass=org.jhotdraw.samples.svg.Main
